truth:
  name: Google Workspace
  source: data/gw.csv
  map: mappings/google-workspace.yml

comparisons:
  - name: Hubspot
    source: data/hubspot.csv
    map: mappings/hubspot.yml

output: test
rules: rules.yml