truth:
  name: Google Workspace
  source: data/google.csv
  map: mappings/google-workspace.yml

comparisons:
  - name: Atlassian
    source: data/atlassian.csv
    map: mappings/atlassian.yml
  - name: Atlassian Jira
    source: data/atlassian.csv
    map: mappings/atlassian-jira.yml
  - name: Monday
    source: data/monday.csv
    map: mappings/monday.yml
    
output: test
rules: rules.yml